# Base configuration for the ESPHome Heart Rate Display
#
# Copyright (c) 2021 Koen Vervloesem
# SPDX-License-Identifier: MIT
#
esphome:
  name: ${node_name}
  platform: ${node_platform}
  board: ${node_board}
  build_path: ./build/${node_name}

# Enable logging
logger:

color:
  - id: color_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: color_red
    red: 100%
    green: 0%
    blue: 0%
  - id: color_white
    red: 100%
    green: 100%
    blue: 100%
  - id: color_black
    red: 0%
    green: 0%
    blue: 0%

# Download Roboto font from https://fonts.google.com/specimen/Roboto
font:
  - file: "fonts/Roboto-Medium.ttf"
    id: font_roboto
    size: 22
  - file: "fonts/Roboto-Medium.ttf"
    id: font_roboto_big
    size: 44
  - file: "fonts/Roboto-Medium.ttf"
    id: font_roboto_10
    size: 10
  - file: "fonts/Roboto-Medium.ttf"
    id: font_roboto_20
    size: 20